In [ ]:
import pandas as pd
import seaborn as sns
from utils import *
import statsmodels.api as sm
from statsmodels.stats.outliers_influence import variance_inflation_factor
from sklearn.linear_model import LinearRegression

PATH="Advertising.csv"

df=pd.read_csv(PATH)

df=df.drop("Unnamed: 0",axis=1)
df

        TV  Radio  Newspaper  Sales
0    230.1   37.8       69.2   22.1
1     44.5   39.3       45.1   10.4
2     17.2   45.9       69.3    9.3
3    151.5   41.3       58.5   18.5
4    180.8   10.8       58.4   12.9
..     ...    ...        ...    ...
195   38.2    3.7       13.8    7.6
196   94.2    4.9        8.1    9.7
197  177.0    9.3        6.4   12.8
198  283.6   42.0       66.2   25.5
199  232.1    8.6        8.7   13.4

[200 rows x 4 columns]

In [7]:
df['TV']=df['TV']*1000
df['Radio']=df['Radio']*1000
df['Newspaper']=df['Newspaper']*1000
df['Sales']=df['Sales']*1000
df

           TV    Radio  Newspaper    Sales
0    230100.0  37800.0    69200.0  22100.0
1     44500.0  39300.0    45100.0  10400.0
2     17200.0  45900.0    69300.0   9300.0
3    151500.0  41300.0    58500.0  18500.0
4    180800.0  10800.0    58400.0  12900.0
..        ...      ...        ...      ...
195   38200.0   3700.0    13800.0   7600.0
196   94200.0   4900.0     8100.0   9700.0
197  177000.0   9300.0     6400.0  12800.0
198  283600.0  42000.0    66200.0  25500.0
199  232100.0   8600.0     8700.0  13400.0

[200 rows x 4 columns]

In [8]:
df.dtypes,df.describe(),df.isnull().sum()

(TV           float64
 Radio        float64
 Newspaper    float64
 Sales        float64
 dtype: object,
                   TV         Radio      Newspaper         Sales
 count     200.000000    200.000000     200.000000    200.000000
 mean   147042.500000  23264.000000   30554.000000  14022.500000
 std     85854.236315  14846.809176   21778.620839   5217.456566
 min       700.000000      0.000000     300.000000   1600.000000
 25%     74375.000000   9975.000000   12750.000000  10375.000000
 50%    149750.000000  22900.000000   25750.000000  12900.000000
 75%    218825.000000  36525.000000   45100.000000  17400.000000
 max    296400.000000  49600.000000  114000.000000  27000.000000,
 TV           0
 Radio        0
 Newspaper    0
 Sales        0
 dtype: int64)

In [9]:
TARGET="Sales"
X=df.drop(TARGET,axis=1)
y=df[TARGET]

In [10]:
for regressor in X:
    regressor_with_constant=sm.add_constant(X[regressor])
    model=sm.OLS(y,regressor_with_constant).fit()
    display(extract_regression_summary(model))

,coef,std err,t,P>|t|,0.025,0.975
const,7032.593549,457.842940,15.360275,1.406300e-35,6129.719269,7935.467829
TV,0.047537,0.002691,17.667626,1.467390e-42,0.042231,0.052843

,coef,std err,t,P>|t|,0.025,0.975
const,9311.638095,562.900496,16.542245,3.561071e-39,8201.588478,10421.687712
Radio,0.202496,0.020411,9.920765,4.354966e-19,0.162244,0.242747

,coef,std err,t,P>|t|,0.025,0.975
const,12351.407069,621.420188,19.876096,4.713507e-49,11125.955598,13576.858540
Newspaper,0.054693,0.016576,3.299591,1.148196e-03,0.022005,0.087381